title: "LEP-XXX: <title>"
labels: ["wip"]
body:
- type: textarea
  id: motivation
  attributes:
    label: "Summary and Motivation"
    description: "What is the problem? What is motivating the creation of the proposal? Be brief. Use bullets. Make it easy to scan. If details are needed for clarity, adde them after the bullets."
    placeholder: |
      - Why is this proposal important? Describe the pain or improvement we hope to fix.
      - What is the cost of not accepting this proposal now?
      - Which stakeholders would benefit from this proposal?

      Add any verbose descriptions or details after your summarized bullets above.
- type: textarea
  id: solution
  attributes:
    label: "Solution and Benefits"
    description: "Summarize the solution and its benefits. Outline the steps required to execute the proposed solution. These steps should be actionable upon acceptance of the proposal by all stakeholders. They should be clear enough to be actionable by the executing stakeholder... consider that this may not be the proposal's author."
    placeholder: |
      - Briefly describe the solution and why it's beneficial to stakeholders.
      - Outline high-level steps toward completion of the solution.
      - What are the upfront costs?
      - What are on-going costs?
      - Which stakeholders would want to understand and/or approve these costs.
      - If the solution requires ongoing maintenance, describe the costs and effort required. How long will this ongoing maintenance be required?
- type: textarea
  id: risks
  attributes:
    label: "Risks and Mitigations"
    description: "Outline potential ways this proposal's solution might fail or cause problems. Consider the entire lifecycle of the solution. Before, during, and after delivery. How would be prevent failure?"
    placeholder: |
      <brief description of a single risk concern>

      Describe the risk in further detail and how it might occur.

      (optional: Briefly describe how we might mitigate this risk from occurring.)
- type: textarea
  id: acceptance
  attributes:
    label: "Acceptance Criteria"
    description: "Which stakeholders will validate the completion of this proposal. If the proposal is an on-going solution, this should indicate how much work is needed for the solution to be passively maintained."
    placeholder: |
      - {Stakeholder} verifies that {Feature} can do {Benefit} {given {Conditions}}
- type: checkboxes
  attributes:
    label: "Proposal Submission Steps"
    options:
    - label: "Title: briefly describes the proposed change in 5-10 words. Replace `XXX` with the next sequential number."
      required: true
    - label: "Summary and Motivation: clearly outline the problem, what motivates us to solve this problem, and the benefits of the proposed solution"
      required: true
    - label: "(optional) Solution and Benefits: if known, describe with detail the work required to execute the proposed solution"
    - label: "Risks and Mitigations: clearly outline all of the known risks and potential mitigations"
      required: true
    - label: "(optional) Acceptance Criteria: if known, describe the conditions which complete this proposal"
