title: "DRAFT: <title> "
labels: ["wip"]
body:
- type: checkboxes
  attributes:
    label: "Proposal Submission Steps"
    description: "test"
- type: textarea
  id: motivation
  attributes:
    label: "Motivation and Benefits"
    description: "What is motivating the creation of the proposal? Be brief. Use bullets. Make it easy to scan. If details are needed for clarity, adde them after the bullets."
    placeholder: |
      - Why is this proposal important? Describe the pain or improvement we hope to fix.
      - What is the cost of not accepting this proposal now?
      - Which stakeholders would benefit from this proposal?

      Add any verbose descriptions or details after your summarized bullets above.
- type: textarea
  id: costs
  attributes:
    label: "Costs"
    description: "Outline expected time, money, and overhead costs. One-time vs on-going. Consider planning, design, development, infrastructure, production support."
    placeholder: |
      - What are the upfront costs?
      - What are on-going costs?
      - Which stakeholders would want to understand and/or approve these costs.
- type: textarea
  id: risks
  attributes:
    label: "Risks and Mitigations"
    description: "Outline potential ways this proposal's solution might fail or cause problems. Consider the entire lifecycle of the solution. Before, during, and after delivery."
    placeholder: |
      ### <brief description of a single risk concern>

      Describe the risk in further detail and how it might occur.

      (optional: Briefly describe how we might mitigate this risk from occurring.)

      ### (repeat as needed)
- type: textarea
  id: solution
  attributes:
    label: "Solution"
    description: "Outline the steps required to execute the proposed solution. These steps should be actionable upon acceptance of the proposal by all stakeholders. They should be clear enough to be actionable by the executing stakeholder... consider that this may not be the proposal's author."
    placeholder: |
      1. Step one of solution.
      2. Step two of solution.

      alternatively... if steps are not necessarily sequential, you could use bullets:

      - Solution component #1
      - Solution component #2
- type: textarea
  id: acceptance
  attributes:
    label: "Acceptance Criteria"
      description: "Which stakeholders will validate the completion of this proposal. If the proposal is an on-going solution, this should indicate how much work is needed for the solution to be passively maintained."
      placeholder: |
        - {Stakeholder} verifies that {Feature} can do {Benefit} {given {Conditions}}
